# Server configuration
server.port=8080
server.servlet.context-path=/

# Thymeleaf configuration
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html

# Development tool configuration
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

# Security configuration
spring.security.user.name=Dawn
spring.security.user.password=666666
