server.port=8084
spring.application.name=auth-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# QQ邮箱SMTP配置
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=a23_0903@qq.com
spring.mail.password=zygroomtnvgtbibf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true